name: clang-tidy-review

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Optionally generate compile_commands.json
    - uses: ZedThree/clang-tidy-review@v0.14.0
      id: review
      with:
        cmake_command: cmake -S . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
        build_dir: build

    # Uploads an artefact containing clang_fixes.json
    - uses: ZedThree/clang-tidy-review/upload@v0.14.0
      id: upload-review

    # If there are any comments, fail the check
    - if: steps.review.outputs.total_comments > 0
      run: exit 1
