name: clang-tidy

on:
  pull_request:
    paths-ignore:
      - 'documentation/**'
      - '.github/workflows/documentation.yml'
  push:
    paths-ignore:
      - 'documentation/**'
      - '.github/workflows/documentation.yml'

jobs:
  clang-tidy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure
        run: cmake -S . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
      - name: clang-tidy
        run: "clang-tidy --format-style=file --warnings-as-errors=* -p build $(git ls-files 'include/**/*.hpp')"
