name: windows

on:
  pull_request:
    paths-ignore:
      - 'documentation/**'
      - '.github/workflows/documentation.yml'
  push:
    paths-ignore:
      - 'documentation/**'
      - '.github/workflows/documentation.yml'

jobs:
  build:
    runs-on: ${{matrix.config.os}}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: windows-2022, vs: "Visual Studio 2022" }
          - { os: windows-2025, vs: "Visual Studio 2022" }
        build: [ Debug, Release ]
        platform: [ Win32, x64 ]

    name: "${{matrix.config.vs}}:${{matrix.platform}}:${{matrix.build}}"
    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -A ${{matrix.platform}}

      - name: Build
        run: cmake --build . --config ${{matrix.build}}

      - name: Tests
        run: ctest --output-on-failure -C ${{matrix.build}}
